if(SDK_LIBS_STATIC)
    set(SDK_LIBS_TYPE static)
else()
    set(SDK_LIBS_TYPE dynamic)
endif()

set (BUILD_MDW_PLATFORMS_HW_PATH ${BUILD_MDW_PLATFORMS_PATH}/hw)
set (BUILD_MDW_PLATFORMS_MEDIA_PATH ${BUILD_MDW_PLATFORMS_PATH}/media)
set (BUILD_MDW_PLATFORMS_SMART_PATH ${BUILD_MDW_PLATFORMS_PATH}/smart)
set (BUILD_MDW_PLATFORMS_AOV_PATH ${BUILD_MDW_PLATFORMS_PATH}/aov)


# 设置MDW_PLATFORMS 源文件路径
set(BUILD_MDW_PLATFORMS_SRC_PATH
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/comm/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/sys/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/video/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/osd/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/smart/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/audio/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/isp/
    ${BUILD_MDW_PLATFORMS_HW_PATH}/${BUILD_SRC}
  )

# 设置MDW_PLATFORMS 头文件路径
set(BUILD_MDW_PLATFORMS_INC_PATH 
    ${BUILD_MDW_PLATFORMS_PATH}/${BUILD_INC}
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/${BUILD_INC}
    ${BUILD_MDW_PLATFORMS_HW_PATH}/${BUILD_INC}
    ${BUILD_PROJECT_SDK_PATH}/release/include
    ${BUILD_PROJECT_SDK_PATH}/release/include/isp
    ${BUILD_PROJECT_SDK_PATH}/release/include/isp/maruko/
    ${BUILD_PROJECT_SDK_PATH}/release/include/ipu/maruko/
  )

#添加link文件
set(BUILD_MDW_PLATFORMS_LINK_PATH
    ${BUILD_PROJECT_SDK_PATH}/release/chip/i6c/ipc/common/uclibc/9.1.0/mi_libs/${SDK_LIBS_TYPE}
    ${BUILD_PROJECT_SDK_PATH}/release/chip/i6c/sigma_common_libs/uclibc/9.1.0/${SDK_LIBS_TYPE}
  )

#添加link文件
set(BUILD_MDW_PLATFORMS_LINK_LIB
    mi_venc mi_rgn mi_ldc mi_vif mi_common cam_os_wrapper
    mi_sys mi_isp mi_scl mi_sensor
    mi_ai mi_ao
    cus3a ispalgo
    APC_LINUX BF_2MIC_LINUX
  )
if(PQTOOL)
    list(APPEND BUILD_MDW_PLATFORMS_LINK_LIB mi_iqserver)
endif()

if(MODULE_SMART)
	list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/${BUILD_SRC})
	list(APPEND BUILD_MDW_PLATFORMS_INC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/${BUILD_INC})
  if(MODULE_SMART_PD)
    list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/pd/${BUILD_SRC})
    list(APPEND BUILD_MDW_PLATFORMS_INC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/pd/${BUILD_INC})
    list(APPEND BUILD_MDW_PLATFORMS_LINK_LIB sstaralgo_dt_dynamic_static_detect mi_ipu cam_fs_wrapper)
	endif()
  if(MODULE_SMART_FD)
    list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/fd/${BUILD_SRC})
    list(APPEND BUILD_MDW_PLATFORMS_INC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/fd/${BUILD_INC})
  endif()
  if(MODULE_SMART_PVD)
    list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/pvd/${BUILD_SRC})
    list(APPEND BUILD_MDW_PLATFORMS_INC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/pvd/${BUILD_INC})
  endif()
endif()

if(MODULE_AOV)
	list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_AOV_PATH}/${BUILD_SRC})
	list(APPEND BUILD_MDW_PLATFORMS_INC_PATH ${BUILD_MDW_PLATFORMS_AOV_PATH}/${BUILD_INC})
endif()

if(MODULE_MEDIA_AUDIO)
	if(MODULE_AUDIO_ALGO_AEC)
		list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/audio/aec)
		list(APPEND BUILD_MDW_PLATFORMS_LINK_LIB AEC_LINUX)
	endif()
endif()