if(SDK_LIBS_STATIC)
    set(SDK_LIBS_TYPE static)
else()
    set(SDK_LIBS_TYPE dynamic)
endif()

set (BUILD_MDW_PLATFORMS_HW_PATH ${BUILD_MDW_PLATFORMS_PATH}/hw)
set (BUILD_MDW_PLATFORMS_MEDIA_PATH ${BUILD_MDW_PLATFORMS_PATH}/media)
set (BUILD_MDW_PLATFORMS_SMART_PATH ${BUILD_MDW_PLATFORMS_PATH}/smart)
set (BUILD_MDW_PLATFORMS_AOV_PATH ${BUILD_MDW_PLATFORMS_PATH}/aov)


# 设置MDW_PLATFORMS 源文件路径
set(BUILD_MDW_PLATFORMS_SRC_PATH
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/comm/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/sys/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/video/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/osd/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/smart/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/audio/
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/isp/
    ${BUILD_MDW_PLATFORMS_HW_PATH}/${BUILD_SRC}
  )

# 设置MDW_PLATFORMS 头文件路径
set(BUILD_MDW_PLATFORMS_INC_PATH 
    ${BUILD_MDW_PLATFORMS_PATH}/${BUILD_INC}
    ${BUILD_MDW_PLATFORMS_MEDIA_PATH}/${BUILD_INC}
    ${BUILD_MDW_PLATFORMS_HW_PATH}/${BUILD_INC}
    ${BUILD_PROJECT_SDK_PATH}/include
    ${BUILD_PROJECT_SDK_PATH}/libs/mpp/include/algstore
    ${BUILD_PROJECT_SDK_PATH}/include/algstore
  )

#添加link文件
set(BUILD_MDW_PLATFORMS_LINK_PATH
    ${BUILD_PROJECT_SDK_PATH}/usr/lib/${SDK_LIBS_TYPE}
    ${BUILD_PROJECT_SDK_PATH}/usr/lib/${SDK_LIBS_TYPE}/algstore
  )

#添加link文件

set(_ANJ_TS_SENSOR_CMAKE ${BUILD_MDW_PLATFORMS_PATH}/sensors/${TS_SENSOR}.cmake)
include(${_ANJ_TS_SENSOR_CMAKE})

set(BUILD_MDW_PLATFORMS_LINK_LIB
mpi cve ui_uart
aiisp isp_hal vpu tinyalsa algaiisp
algaiisp_rfr algutil_cv trp frm_mgr 3a
dof sensor omx hw_env mpp_sys isp sen_modules rne_rt_g3 algcommon
isp_driver api cmdr fw_utils ${ANJ_TS_SENSOR_LIBS}
rne_common rne_pal_linux_a35 buf_mgr json_convert isp_osif cjson isp_utils
)

# anjflash 仅需 MMZ mmap，直接链接 mpp_sys 即可
set(BUILD_ANJFLASH_LINK_LIB mpp_sys)

if(MODULE_SMART)
	list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/${BUILD_SRC})
	list(APPEND BUILD_MDW_PLATFORMS_INC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/${BUILD_INC})
  if(MODULE_SMART_PD)
    list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/pd/${BUILD_SRC})
    list(APPEND BUILD_MDW_PLATFORMS_INC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/pd/${BUILD_INC})
    list(APPEND BUILD_MDW_PLATFORMS_LINK_LIB algbodydetect3)
	endif()
  if(MODULE_SMART_FD)
    list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/fd/${BUILD_SRC})
    list(APPEND BUILD_MDW_PLATFORMS_INC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/fd/${BUILD_INC})
    list(APPEND BUILD_MDW_PLATFORMS_LINK_LIB algfacedetect)
  endif()
  if(MODULE_SMART_PVD)
    list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/pvd/${BUILD_SRC})
    list(APPEND BUILD_MDW_PLATFORMS_INC_PATH ${BUILD_MDW_PLATFORMS_SMART_PATH}/pvd/${BUILD_INC})
    list(APPEND BUILD_MDW_PLATFORMS_LINK_LIB algmod8c)
  endif()
endif()

if(MODULE_AOV)
	list(APPEND BUILD_MDW_PLATFORMS_SRC_PATH ${BUILD_MDW_PLATFORMS_AOV_PATH}/${BUILD_SRC})
	list(APPEND BUILD_MDW_PLATFORMS_INC_PATH ${BUILD_MDW_PLATFORMS_AOV_PATH}/${BUILD_INC})
endif()

if(MODULE_MEDIA_AUDIO)
  list(APPEND BUILD_MDW_PLATFORMS_LINK_LIB
    algvqesolwebrtc3a algwebrtc3a algnoisegate
    algmmsens alganrnn algomlsa algmmsens
    NE10_intrinsic algutil_sp)
  if(MODULE_AUDIO_ALGO_AEC)
    #list(APPEND BUILD_MDW_PLATFORMS_LINK_LIB AEC_LINUX)
  endif()
endif()

add_definitions("-DDX5326")
