#ifndef __ANJ_WEB_H__
#define __ANJ_WEB_H__

enum WEB_SERVER_HTTP_STATUS_CODE {
    WEB_SERVER_HTTP_STATUS_CODE_OK = 200,
    WEB_SERVER_HTTP_STATUS_CODE_ACCEPTED = 202,
    WEB_SERVER_HTTP_STATUS_CODE_AMBIGUOUS = 300,
    WEB_SERVER_HTTP_STATUS_CODE_USEPROXY = 305,
    WEB_SERVER_HTTP_STATUS_CODE_BADREQUEST = 400,
    WEB_SERVER_HTTP_STATUS_CODE_FORBIDDEN  = 403,
    WEB_SERVER_HTTP_STATUS_CODE_NOTFOUND = 404,
    WEB_SERVER_HTTP_STATUS_CODE_REQUESTTIMEOUT = 408,
    WEB_SERVER_HTTP_STATUS_CODE_CONFLICT = 409,
    WEB_SERVER_HTTP_STATUS_CODE_BADGATEWAY = 502,
    WEB_SERVER_HTTP_STATUS_CODE_MALLOC_ERROR = 999,
};

enum WEB_SERVER_RETURN_STATUS_CODE {
    WEB_SERVER_RETURN_STATUS_CODE_SUCCESS = 0,
    WEB_SERVER_RETURN_STATUS_CODE_FAILURE = 1,
    WEB_SERVER_RETURN_STATUS_CODE_CHECK_PARAMENT_ERROR = 2,
    WEB_SERVER_RETURN_STATUS_CODE_HANDLE_ERROR = 3,
};



int anj_web_init();

int anj_web_uninit();

#endif
