### 设备platform 类型
set (BUILD_SRC src)
set (BUILD_INC inc)

### PREBUILD
set (BUILD_PREBUILD_PATH ${PROJECT_SOURCE_DIR}/prebuild)

### PROJECT
set (BUILD_PROJECT_PATH ${PROJECT_SOURCE_DIR}/project)
set (BUILD_PROJECT_TARGET_PATH ${BUILD_PROJECT_PATH}/${BUILD_PROJECT_NAME})


### APP
set (BUILD_APP_PATH ${PROJECT_SOURCE_DIR}/app)

### DAEMON
set (BUILD_DAEMON_PATH ${PROJECT_SOURCE_DIR}/daemon)

### TOOLS
set (BUILD_ANJ_FLASH_PATH ${PROJECT_SOURCE_DIR}/tools/anjflash)
set (BUILD_ANJ_REC_PATH ${PROJECT_SOURCE_DIR}/tools/anjrec)

### MODULE
set (BUILD_MODULE_PATH ${PROJECT_SOURCE_DIR}/module)
set (BUILD_MODULE_MBUF_PATH ${BUILD_MODULE_PATH}/mbuf)
set (BUILD_MODULE_NET_PATH ${BUILD_MODULE_PATH}/net)
set (BUILD_MODULE_SERVICE_PATH ${BUILD_MODULE_PATH}/service)

### MLW
set (BUILD_MDW_PATH ${PROJECT_SOURCE_DIR}/middleware)

### PLATFORM
set (BUILD_MDW_PLATFORMS_PATH ${BUILD_MDW_PATH}/platforms/${BUILD_PLATFORMS_NAME})

if(ANJ_BUILD_ALL_MODULES)
  set(MODULE_PTZ ON)
  set(MODULE_PTZ_DRV ON)
  set(MODULE_PTZ_PWM ON)
  set(MODULE_PTZ_IIC ON)
  set(MODULE_SDCARD ON)
  set(FLASH_TYPE_NOR ON)
  set(MODULE_NFS ON)
  set(MODULE_MCU ON)
  set(MODULE_AOV OFF)
  set(MODULE_ZXING ON)
  set(MODULE_WAVE ON)
  set(MODULE_BATTERY ON)
  set(MODULE_GYRO ON)
  set(MODULE_GYRO_ICM42607P ON)
  set(MODULE_BLUETOOTH ON)
  set(MODULE_MEDIA_AUDIO ON)
  set(MODULE_MEDIA_MP3 ON)
  set(MODULE_MEDIA_AAC ON)
  set(MODULE_AUDIO_ALGO_AEC ON)
  set(MODULE_MEDIA_OSD ON)
  set(MODULE_SNAP_SOFT ON)
  set(MODULE_SNAP_HARD ON)
  set(MODULE_SMART ON)
  set(MODULE_SMART_MD ON)
  set(MODULE_SMART_PD ON)
  set(MODULE_SMART_FD ON)
  set(MODULE_SMART_PVD ON)
  set(MODULE_SREVICE_28181 ON)
  set(MODULE_SREVICE_ONVIF ON)
  set(ONVIF_VERSION_SIMPLE OFF)
  set(ONVIF_VERSION_FULL ON)
  set(MODULE_SREVICE_HIK ON)
  set(MODULE_SREVICE_RTSP_ENABLE ON)
  set(MODULE_SREVICE_RTSP ON)
  set(MODULE_SREVICE_RTSP_LITE ON)
  set(MODULE_SREVICE_ANJSER ON)
  set(AIOT_SERVER ON)
  set(ALI_SERVER OFF)
  set(MODULE_CLOUD_STORAGE ON)
  set(AIOT_CLOUD_STORAGE ON)
  set(CT_CLOUD_STORAGE ON)
  set(MODULE_SREVICE_ANJWEB ON)
  set(MODULE_SREVICE_H5LIVE ON)
  set(MODULE_SREVICE_RTMP ON)
  set(MODULE_SERVICE_HTTP ON)
  set(MODULE_SERVICE_FTPEMAIL ON)
  set(MODULE_NET_WIRE ON)
  set(MODULE_NET_WIFI ON)
  set(MODULE_NET_4G ON)
endif()

include (${BUILD_MDW_PATH}/middleware_option.cmake)
include (${BUILD_MDW_PLATFORMS_PATH}/platform_option.cmake)
include (${BUILD_MODULE_PATH}/module_option.cmake)
