set (BUILD_MDW_COMM_PATH ${BUILD_MDW_PATH}/comm)
set (BUILD_MDW_HWCTRL_PATH ${BUILD_MDW_PATH}/hwctrl)
set (BUILD_MDW_REC_PATH ${BUILD_MDW_PATH}/rec)
set (BUILD_MDW_SMART_PATH ${BUILD_MDW_PATH}/smart)

### 设置头文件
set(BUILD_MDW_INC_LIST
     ${BUILD_MDW_COMM_PATH}/${BUILD_INC}
     ${BUILD_MDW_COMM_PATH}/${BUILD_INC}/lame
     ${BUILD_MDW_COMM_PATH}/${BUILD_INC}/fdk-aac
     ${BUILD_MDW_HWCTRL_PATH}/${BUILD_INC}
     ${BUILD_MDW_REC_PATH}/${BUILD_INC}
     ${BUILD_MDW_PATH}/media/inc
     ${BUILD_MDW_SMART_PATH}/${BUILD_INC}
     )
### 设置源文件
set(BUILD_MDW_SRC_LIST
     ${BUILD_MDW_COMM_PATH}/${BUILD_SRC}
     ${BUILD_MDW_HWCTRL_PATH}/${BUILD_SRC}
     ${BUILD_MDW_REC_PATH}/${BUILD_SRC}
     ${BUILD_MDW_SMART_PATH}/${BUILD_SRC}
     ${BUILD_MDW_PATH}/media/src
     )
