#ifndef __ONVIF_NOTIFY_H__
#define __ONVIF_NOTIFY_H__

#include "sys_inc.h"
#include "protocol_queue.h"
#include "onvif.h"
#include "para.h"

typedef enum {
	ALARM_CODE_MOTION_TRUE=50,
	ALARM_CODE_MOTION_FALSE=51,
	ALARM_EVENT_STATE_TRUE=52,
	ALARM_EVENT_STATE_FALSE=53,
	ALARM_CODE_IO_TRUE=54,
	ALARM_CODE_IO_FALSE=55,
	ALARM_IO_INSTATE_TRUE=56,
	ALARM_IO_INSTATE_FALSE=57,	
	ALARM_CODE_OCALL_CALLOUT=58,//onvif_callout
	ALARM_CODE_OCALL_THROUGH=59,//onvif_through
	ALARM_CODE_OCALL_HANGUP=60,//onvif_hangup
	ALARM_CODE_OCALL_TOHANGUP=61,//onvif_timeout_hangup
	ALARM_CODE_PD_TRUE=62,
	ALARM_CODE_PD_FALSE=63,
	ALARM_CODE_VEHICEL_TRUE=64,
	ALARM_CODE_VEHICEL_FALSE=65,
	ALARM_CODE_NON_VEHICEL_TRUE=66,
	ALARM_CODE_NON_VEHICEL_FALSE=67,
	
	ALARM_CODE_FACE_TRUE=68,
	ALARM_CODE_FACE_FALSE=69,
	
	ALARM_CODE_GATE_TRUE=70,
	ALARM_CODE_GATE_FALSE=71,
	
	ALARM_CODE_REGION_DETECT_ENTER_TRUE=72,
	ALARM_CODE_REGION_DETECT_ENTER_FALSE=73,
	
	ALARM_CODE_REGION_DETECT_LEAVE_TRUE=74,
	ALARM_CODE_REGION_DETECT_LEAVE_FALSE=75,
	
	ALARM_CODE_REGION_DETECT_STAY_TRUE=76,
	ALARM_CODE_REGION_DETECT_STAY_FALSE=77,

	ALARM_CODE_FIRE_TRUE=78,
	ALARM_CODE_FIRE_FALSE=79,

	ALARM_CODE_LRP_TRUE=80,
	ALARM_CODE_LRP_FALSE=81,
}AjAlarmCode2;

void onvif_event_mgr_init(void);

int msg_send_onvifevent(FRAME_ENTRY *frame, ALARM_MSG_DATA *msg);

int onvif_alarm_event_handle(const ALARM_MSG_DATA *alarm);

void *onvif_alarm_thr(void *arg);

#endif 


