#ifndef _WIS_STREAMER_H_
#define _WIS_STREAMER_H_

#define RTSP_READER_ID				0x888
#define MAX_RTSP_SESSION_TIMEOUT	180//120
//#define MAX_RTSP_CLIENT_SESSION	    PRODUCT_RTSP_MAX_CLIENT_SESSION
#define MIN_RTSP_CLIENT_SESSION	    1


#endif
