set(TARGET_NAME anjrtsp)
set(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/out/lib/)

aux_source_directory(${CMAKE_CURRENT_SOURCE_DIR}/src SRC_LIST)
aux_source_directory(${CMAKE_CURRENT_SOURCE_DIR}/src/rtsp_server/anjrtsp SRC_LIST)
aux_source_directory(${CMAKE_CURRENT_SOURCE_DIR}/src/rtsp_server/BasicUsageEnvironment SRC_LIST)
aux_source_directory(${CMAKE_CURRENT_SOURCE_DIR}/src/rtsp_server/groupsock SRC_LIST)
aux_source_directory(${CMAKE_CURRENT_SOURCE_DIR}/src/rtsp_server/liveMedia SRC_LIST)
aux_source_directory(${CMAKE_CURRENT_SOURCE_DIR}/src/rtsp_server/UsageEnvironment SRC_LIST)
add_library(${TARGET_NAME} STATIC ${SRC_LIST})
anj_module_prepare_output(${TARGET_NAME} "service/rtsp")

foreach (MODULE_INC_LIST_ ${MODULE_INC_LIST})
    target_include_directories(${TARGET_NAME} PRIVATE ${MODULE_INC_LIST_})
endforeach()
