#ifndef _REC_MOV_DEF_H_

#define _REC_MOV_DEF_H_

#include "media_util.h"

#ifdef __cplusplus
extern "C"
{
#endif

#define REC_FILE_STARTCODE (0xBE5AA5EB)
#define REC_SDCAR_MIN_SIZE              ((unsigned long long)3*1024*1024*1024)  //最少需要3G空间
#define REC_SDCAR_REMAIN_SIZE           ((unsigned long long)2*1024*1024*1024)  //最少剩余2G空间

#define REC_READ_FRAME_BUF_SIZE (512 * 1024) // 默认读帧大小
#define REC_MAX_FRAME_BUF_SIZE (1024 * 1024) // 最大帧
#define REC_MAX_AUDIO_FRAME_BUF_SIZE    (5*1024)    //最大帧

/**************************************************** 索引文件相关宏定义 *************************************************/
#define REC_INDEX_MAIN_FILE_NAME "/anj00.bin"     // 索引文件名字
#define REC_INDEX_MAIN_FILE_NAME_BAK "/anj01.bin" // 索引备份文件名字
#define REC_INDEX_MAIN_FILE_SIZE (1024 * 1024)    // 索引文件大小
#define REC_MEDIA_MAX_FILE_NUM (4096)             // 512G/128MB预分配文件数上限
#define REC_MEDIA_BAD_BLOCK_MAP_SIZE (REC_MEDIA_MAX_FILE_NUM / 8)

#define REC_INDEX_VERSION_256M (0)              // 256MB预分配
#define REC_INDEX_VERSION_128M (1)              // 128MB预分配

#define REC_MEDIA_WRITE_BUFFER          (64 * 1024)

/**************************************************** 媒体文件相关宏定义 *************************************************/
#define REC_MEDIA_FILE_NAME "%s/anj%06d.mp4"        // 索引文件大小
#define REC_MEDIA_FILE_SIZE (128 * 1024 * 1024)        // 媒体单文件大小
#define REC_MEDIA_MAX_FPS (250 * REC_MEDIA_BUF_FPS) // 最大存储 256000FPS，大概250分钟 注意：REC_MEDIA_BUF_FPS倍数
#define REC_MEDIA_BUF_FPS (1024)                    // 最大缓存1024帧，大概1分钟

#define REC_FILE_REMAIN_SIZE (1024 * 1024)      // 用于切换文件时片段 小于这个余量且为I帧时切换文件
#define REC_FILE_REMAIN_FPS (200)               // 用于切换文件时片段 小于这个余量且为I帧时切换文件
#define REC_FILE_FFLUSH_FPS (REC_MEDIA_BUF_FPS) // 每N帧写一次缓冲

#define MOV_BOX_MOOV_STBL_FRAME_SIZE(baseBytes, perSize, frames) (baseBytes + (perSize * frames))
/*  MOOV VTRAK MINF STSD STTS STSS STSC STSZ STCO*/
#define MOV_BOX_MOOV_STBL_STTS_HEAD_SIZE (16)
#define MOV_BOX_MOOV_STBL_STSS_HEAD_SIZE (16)
#define MOV_BOX_MOOV_STBL_STSC_HEAD_SIZE (16)
#define MOV_BOX_MOOV_STBL_STSZ_HEAD_SIZE (20)
#define MOV_BOX_MOOV_STBL_STCO_HEAD_SIZE (16)

#define MOV_BOX_MOOV_STBL_STTS_SIZE(frameIndex) (MOV_BOX_MOOV_STBL_FRAME_SIZE(MOV_BOX_MOOV_STBL_STTS_HEAD_SIZE, 8, frameIndex))  // size+stts+ver&flag+count+ count*(fps(4)+perchunktimes(4))
#define MOV_BOX_MOOV_STBL_STSS_SIZE(frameIndex) (MOV_BOX_MOOV_STBL_FRAME_SIZE(MOV_BOX_MOOV_STBL_STSS_HEAD_SIZE, 4, frameIndex))  // size+stts+ver&flag+count+ count*(KerFramepos)
#define MOV_BOX_MOOV_STBL_STSC_SIZE(frameIndex) (MOV_BOX_MOOV_STBL_FRAME_SIZE(MOV_BOX_MOOV_STBL_STSC_HEAD_SIZE, 12, frameIndex)) // size+stts+ver&flag+count+ count*(first_chunk+samples_per_chunk+sample_description_index)
#define MOV_BOX_MOOV_STBL_STSZ_SIZE(frameIndex) (MOV_BOX_MOOV_STBL_FRAME_SIZE(MOV_BOX_MOOV_STBL_STSZ_HEAD_SIZE, 4, frameIndex))  // size+stts+ver&flag+flag(0)+count+count*(bytes)
#define MOV_BOX_MOOV_STBL_STCO_SIZE(frameIndex) (MOV_BOX_MOOV_STBL_FRAME_SIZE(MOV_BOX_MOOV_STBL_STCO_HEAD_SIZE, 4, frameIndex))  // size+stts+ver&flag+count+ count*(offset)

    /* MP4 --- FTYP->MDAT->FREE->MOV()  */

#define MOV_BOX_STU_SIZE (8) // size_t(4bit) + tpye(4bit)

/*  FTYP */
#define MOV_BOX_FTYP_SIZE (28)     // 0x1C FTYP + MDAT+size()
#define MOV_BOX_FTYP_START_POS (0) // 0x1C FTYP + MDAT+size()

/*  MOOV */
#define MOV_BOX_MOOV_SIZE (MOV_BOX_STU_SIZE + MOV_BOX_MOOV_MVHD_SIZE + MOV_BOX_MOOV_VTRAK_SIZE + MOV_BOX_MOOV_ATRAK_SIZE) // MOOV总大小
#define MOV_BOX_MOOV_STSRT_POS (MOV_BOX_FTYP_START_POS + MOV_BOX_FTYP_SIZE)                                               // 28  MOOV起始位置

/*  MOOV MVHD */
#define MOV_BOX_MOOV_MVHD_SIZE (108)                                            // MP4 fix
#define MOV_BOX_MOOV_MVHD_START_POS (MOV_BOX_MOOV_STSRT_POS + MOV_BOX_STU_SIZE) // 44  MOOV MVHD起始位置

/*  MOOV VTRAK */
#define MOV_BOX_MOOV_VTRAK_SIZE (MOV_BOX_STU_SIZE + MOV_BOX_MOOV_VTRAK_TKHD_SIZE + MOV_BOX_MOOV_VTRAK_EDTS_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_SIZE)
#define MOV_BOX_MOOV_VTRAK_START_POS (MOV_BOX_MOOV_MVHD_START_POS + MOV_BOX_MOOV_MVHD_SIZE) // 152 MOOV VTRAK起始位置

/*  MOOV VTRAK TKHD */
#define MOV_BOX_MOOV_VTRAK_TKHD_SIZE (92) // MP4 fix
#define MOV_BOX_MOOV_VTRAK_TKHD_START_POS (MOV_BOX_MOOV_VTRAK_START_POS + MOV_BOX_STU_SIZE)

/*  MOOV VTRAK EDTS */
#define MOV_BOX_MOOV_VTRAK_EDTS_SIZE (MOV_BOX_MOOV_VTRAK_EDTS_ELST_SIZE + MOV_BOX_STU_SIZE) // MP4 fix
#define MOV_BOX_MOOV_VTRAK_EDTS_START_POS (MOV_BOX_MOOV_VTRAK_TKHD_START_POS + MOV_BOX_MOOV_VTRAK_TKHD_SIZE)

/*  MOOV VTRAK EDTS ELST*/
// 视频不加delay count = 1
#define MOV_BOX_MOOV_VTRAK_EDTS_ELST_SIZE (16 + (12 * 1)) // size+stts+ver&flag+count+count*(12 duration+time+rate)
#define MOV_BOX_MOOV_VTRAK_EDTS_ELST_START_POS (MOV_BOX_MOOV_VTRAK_EDTS_START_POS + MOV_BOX_STU_SIZE)

/*  MOOV VTRAK MDIA */
#define MOV_BOX_MOOV_VTRAK_MDIA_SIZE (MOV_BOX_STU_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MDHD_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_HDLR_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MINF_SIZE)
#define MOV_BOX_MOOV_VTRAK_MDIA_START_POS (MOV_BOX_MOOV_VTRAK_EDTS_START_POS + MOV_BOX_MOOV_VTRAK_EDTS_SIZE)

/*  MOOV VTRAK MDHD */
#define MOV_BOX_MOOV_VTRAK_MDIA_MDHD_SIZE (32) // MP4 fix
#define MOV_BOX_MOOV_VTRAK_MDIA_MDHD_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_START_POS + MOV_BOX_STU_SIZE)

/*  MOOV VTRAK HDLR */
#define MOV_BOX_MOOV_VTRAK_MDIA_HDLR_SIZE (45) // MP4 fix
#define MOV_BOX_MOOV_VTRAK_MDIA_HDLR_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_MDHD_START_POS + MOV_BOX_MOOV_VTRAK_MDIA_MDHD_SIZE)

/*  MOOV VTRAK MINF */
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_SIZE (MOV_BOX_STU_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MINF_VMHD_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MINF_DINF_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_SIZE) //
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_HDLR_START_POS + MOV_BOX_MOOV_VTRAK_MDIA_HDLR_SIZE)

/*  MOOV VTRAK MINF VMHD */
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_VMHD_SIZE (20) // MP4 fix
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_VMHD_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_MINF_START_POS + MOV_BOX_STU_SIZE)

/*  MOOV VTRAK MINF DINF */
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_DINF_SIZE (36) // MP4 fix
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_DINF_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_MINF_VMHD_START_POS + MOV_BOX_MOOV_VTRAK_MDIA_MINF_VMHD_SIZE)

/*  MOOV VTRAK MINF STBL */
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_SIZE (MOV_BOX_STU_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSD_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STTS_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSS_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSC_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSZ_SIZE + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STCO_SIZE)
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_MINF_DINF_START_POS + MOV_BOX_MOOV_VTRAK_MDIA_MINF_DINF_SIZE)

/*  MOOV VTRAK MINF STSD STTS STSS STSC STSZ STCO*/
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSD_SIZE (318) // hvcC payload 208, fit larger VPS/SPS/PPS
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSD_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_START_POS + MOV_BOX_STU_SIZE)
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STTS_SIZE (MOV_BOX_MOOV_STBL_STTS_SIZE(REC_MEDIA_MAX_FPS)) // size+stts+ver&flag+count+ count*(fps(4)+perchunktimes(4))
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STTS_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSD_START_POS + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSD_SIZE)
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSS_SIZE (MOV_BOX_MOOV_STBL_STSS_SIZE(REC_MEDIA_MAX_FPS)) // size+stts+ver&flag+count+ count*(KerFramepos)
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSS_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STTS_START_POS + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STTS_SIZE)
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSC_SIZE (MOV_BOX_MOOV_STBL_STSC_SIZE(REC_MEDIA_MAX_FPS)) // size+stts+ver&flag+count+ count*(first_chunk+samples_per_chunk+sample_description_index)
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSC_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSS_START_POS + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSS_SIZE)
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSZ_SIZE (MOV_BOX_MOOV_STBL_STSZ_SIZE(REC_MEDIA_MAX_FPS)) // size+stts+ver&flag+flag(0)+count+count*(bytes)
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSZ_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSC_START_POS + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSC_SIZE)
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STCO_SIZE (MOV_BOX_MOOV_STBL_STCO_SIZE(REC_MEDIA_MAX_FPS)) // size+stts+ver&flag+count+ count*(offset)
#define MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STCO_START_POS (MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSZ_START_POS + MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STSZ_SIZE)

/*  MOOV ATRCK */
#define MOV_BOX_MOOV_ATRAK_SIZE (MOV_BOX_STU_SIZE + MOV_BOX_MOOV_ATRAK_TKHD_SIZE + MOV_BOX_MOOV_ATRAK_EDTS_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_SIZE)
#define MOV_BOX_MOOV_ATRAK_START_POS (MOV_BOX_MOOV_VTRAK_START_POS + MOV_BOX_MOOV_VTRAK_SIZE) // 261267035

/*  MOOV ATRAK TKHD */
#define MOV_BOX_MOOV_ATRAK_TKHD_SIZE (92) // MP4 fix
#define MOV_BOX_MOOV_ATRAK_TKHD_START_POS (MOV_BOX_MOOV_ATRAK_START_POS + MOV_BOX_STU_SIZE)

/*  MOOV ATRAK EDTS */
#define MOV_BOX_MOOV_ATRAK_EDTS_SIZE (MOV_BOX_MOOV_ATRAK_EDTS_ELST_SIZE + MOV_BOX_STU_SIZE) // MP4 fix
#define MOV_BOX_MOOV_ATRAK_EDTS_START_POS (MOV_BOX_MOOV_ATRAK_TKHD_START_POS + MOV_BOX_MOOV_ATRAK_TKHD_SIZE)

/*  MOOV ATRAK EDTS ELST */
// 音频加delay,count = 2
#define MOV_BOX_MOOV_ATRAK_EDTS_ELST_SIZE (16 + (12 * 2)) // size+stts+ver&flag+count+count*(12 duration+time+rate)
#define MOV_BOX_MOOV_ATRAK_EDTS_ELST_START_POS (MOV_BOX_MOOV_ATRAK_EDTS_START_POS + MOV_BOX_STU_SIZE)

/*  MOOV ATRAK MDIA */
#define MOV_BOX_MOOV_ATRAK_MDIA_SIZE (MOV_BOX_STU_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MDHD_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_HDLR_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MINF_SIZE)
#define MOV_BOX_MOOV_ATRAK_MDIA_START_POS (MOV_BOX_MOOV_ATRAK_EDTS_START_POS + MOV_BOX_MOOV_ATRAK_EDTS_SIZE)

/*  MOOV ATRAK MDIA MDHD */
#define MOV_BOX_MOOV_ATRAK_MDIA_MDHD_SIZE (32) // MP4 fix
#define MOV_BOX_MOOV_ATRAK_MDIA_MDHD_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_START_POS + MOV_BOX_STU_SIZE)
/*  MOOV ATRAK MDIA HDLR */
#define MOV_BOX_MOOV_ATRAK_MDIA_HDLR_SIZE (45) // MP4 fix
#define MOV_BOX_MOOV_ATRAK_MDIA_HDLR_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_MDHD_START_POS + MOV_BOX_MOOV_ATRAK_MDIA_MDHD_SIZE)
/*  MOOV ATRAK MDIA MINF */
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_SIZE (MOV_BOX_STU_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MINF_SMHD_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MINF_DINF_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_SIZE) //
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_HDLR_START_POS + MOV_BOX_MOOV_ATRAK_MDIA_HDLR_SIZE)
/*  MOOV ATRAK MDIA SMHD */
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_SMHD_SIZE (16) // MP4 fix
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_SMHD_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_MINF_START_POS + MOV_BOX_STU_SIZE)
/*  MOOV ATRAK MDIA DINF */
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_DINF_SIZE (36) // MP4 fix
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_DINF_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_MINF_SMHD_START_POS + MOV_BOX_MOOV_ATRAK_MDIA_MINF_SMHD_SIZE)
/*  MOOV ATRAK MDIA STBL */
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_SIZE (MOV_BOX_STU_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSD_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STTS_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSC_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSZ_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STCO_SIZE)
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_MINF_DINF_START_POS + MOV_BOX_MOOV_ATRAK_MDIA_MINF_DINF_SIZE)

/*  MOOV ATRAK MDIA STSD MP4A ESDS */
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSD_MP4A_ESDS_SIZE (51)

/*  MOOV ATRAK MDIA STSD MP4A BTRT */
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSD_MP4A_BTRT_SIZE (20)

/*  MOOV ATRAK MDIA STSD STTS STSC STSZ STCO */
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSD_SIZE (52 + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSD_MP4A_ESDS_SIZE + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSD_MP4A_BTRT_SIZE) // MP4 fix
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSD_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_START_POS + MOV_BOX_STU_SIZE)
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STTS_SIZE (MOV_BOX_MOOV_STBL_STTS_SIZE(REC_MEDIA_MAX_FPS)) // size+stts+ver&flag+count+ count*(fps(4)+perchunktimes(4))
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STTS_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSD_START_POS + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSD_SIZE)
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSC_SIZE (MOV_BOX_MOOV_STBL_STSC_SIZE(REC_MEDIA_MAX_FPS)) // size+stts+ver&flag+count+ count*(first_chunk+samples_per_chunk+sample_description_index)
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSC_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STTS_START_POS + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STTS_SIZE)
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSZ_SIZE (MOV_BOX_MOOV_STBL_STSZ_SIZE(REC_MEDIA_MAX_FPS)) // size+stts+ver&flag+flag(0)+count+count*(bytes)
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSZ_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSC_START_POS + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSC_SIZE)
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STCO_SIZE (MOV_BOX_MOOV_STBL_STCO_SIZE(REC_MEDIA_MAX_FPS)) // size+stts+ver&flag+count+ count*(offset)
#define MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STCO_START_POS (MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSZ_START_POS + MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STSZ_SIZE)

#define MOV_BOX_MOOV_MVHD_BUF_SIZE (MOV_BOX_MOOV_VTRAK_START_POS - MOV_BOX_MOOV_STSRT_POS) //  116
#define MOV_BOX_MOOV_VTRACK_BUF_SIZE (MOV_BOX_MOOV_VTRAK_MDIA_MINF_STBL_STTS_START_POS - MOV_BOX_MOOV_STSRT_POS)
#define MOV_BOX_MOOV_ATRACK_BUF_SIZE (MOV_BOX_MOOV_ATRAK_MDIA_MINF_STBL_STTS_START_POS - MOV_BOX_MOOV_ATRAK_START_POS)

#define MOV_BOX_MOOV_TRACK_STTS_BUF_SIZE (MOV_BOX_MOOV_STBL_STTS_SIZE(REC_MEDIA_BUF_FPS))
#define MOV_BOX_MOOV_TRACK_STSS_BUF_SIZE (MOV_BOX_MOOV_STBL_STSS_SIZE(REC_MEDIA_BUF_FPS))
#define MOV_BOX_MOOV_TRACK_STSC_BUF_SIZE (MOV_BOX_MOOV_STBL_STSC_SIZE(REC_MEDIA_BUF_FPS))
#define MOV_BOX_MOOV_TRACK_STSZ_BUF_SIZE (MOV_BOX_MOOV_STBL_STSZ_SIZE(REC_MEDIA_BUF_FPS))
#define MOV_BOX_MOOV_TRACK_STCO_BUF_SIZE (MOV_BOX_MOOV_STBL_STCO_SIZE(REC_MEDIA_BUF_FPS))

/*  FREE */
#define MOV_BOX_FREE_SIZE (2 * 1024 * 1024)
#define MOV_BOX_FREE_START_POS (MOV_BOX_MOOV_ATRAK_START_POS + MOV_BOX_MOOV_ATRAK_SIZE) // 保留字节 FREE字段

/* MDAT */
#define MOV_BOX_MDAT_SIZE (REC_MEDIA_FILE_SIZE - (MOV_BOX_MDAT_START_POS + MOV_BOX_STU_SIZE)) // MDAT总大小
#define MOV_BOX_MDAT_START_POS (MOV_BOX_FREE_START_POS + MOV_BOX_FREE_SIZE)                   // MOOV起始位置

typedef enum
{
    REC_EVENT_NULL_MASK = 0,         // 普通录像1<<0
    REC_EVENT_MOTION_ALARM_MASK = 1, // 移动报警录像1<<1
    REC_EVENT_HUMEN_ALARM_MASK = 2,  // 人形报警录像1<<2
    REC_EVENT_CAR_ALARM_MASK = 3,    // 机动车报警录像1<<3
    REC_EVENT_IO_ALARM_MASK = 4,     // IO报警录像1<<4
    REC_EVENT_NONE_ALARM_MASK,
    REC_EVENT_MODE_MAX
} rec_event_mask_e;

// 录像事件如果0为无录像对应位为1时有效
#define REC_EVENT_CHECK_MASK(iEvent, iMask) (iEvent & (1 << iMask))    // 检测是否有对应人形报警事件
#define REC_EVENT_SET_MASK(iEvent, iMask) (iEvent | (1 << iMask))      // 设置对应报警事件
#define REC_EVENT_CLEAR_MASK(iEvent, iMask) (iEvent & (~(1 << iMask))) // 设置对应报警事件
#define REC_EVENT_ALL 0xFF
#define REC_EVENT_NONE (1 << REC_EVENT_NULL_MASK)                      // 无事件录像

#ifdef __cplusplus
}
#endif

#endif /* !_mov_writer_h_ */
